<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://service.ultra.com.br/logistica/AtualizacaoLojasRest/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/LegadoFault/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/StoreDesc/v1"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:Q4="http://canonico.ultra.com.br/LegadoOutput/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/AddrDesc/v1"
                xmlns:ns1="http://service.ultra.com.br/logistica/Lojas/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/Lojas/v1/WSDLs/LojasV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/AtualizacaoLojasRest.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://service.ultra.com.br/logistica/AtualizacaoLojasRest/v1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JUL 14 00:50:05 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:codigoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store"/>
         </tns:codigoLoja>
         <tns:tipoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_type"/>
         </tns:tipoLoja>
         <tns:nomeLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name"/>
         </tns:nomeLoja>
         <tns:nomeFantasia>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name10"/>
         </tns:nomeFantasia>
         <tns:nomeAbreviado>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name3"/>
         </tns:nomeAbreviado>
         <tns:enderecoPrincipal>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_add1"/>
         </tns:enderecoPrincipal>
         <tns:nomeCidade>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_city"/>
         </tns:nomeCidade>
         <tns:municipio>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:county"/>
         </tns:municipio>
         <tns:uf>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:state"/>
         </tns:uf>
         <tns:classeLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_class"/>
         </tns:classeLoja>
         <tns:gerentes>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_mgr_name"/>
         </tns:gerentes>
         <tns:dataAberturaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_open_date"/>
         </tns:dataAberturaLoja>
         <tns:dataFechamentoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_close_date"/>
         </tns:dataFechamentoLoja>
         <tns:telefoneLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:phone_number"/>
         </tns:telefoneLoja>
         <tns:emailLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:email"/>
         </tns:emailLoja>
         <tns:areaTotalLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:total_square_ft"/>
         </tns:areaTotalLoja>
         <tns:areaVendaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:selling_square_ft"/>
         </tns:areaVendaLoja>
         <tns:areaUtilizavelLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:linear_distance"/>
         </tns:areaUtilizavelLoja>
         <tns:lojaPossuiEstoque>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:stockholding_ind"/>
         </tns:lojaPossuiEstoque>
         <tns:codigoDistritoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:district"/>
         </tns:codigoDistritoLoja>
         <tns:numeroDiasRecebimento>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:start_order_days"/>
         </tns:numeroDiasRecebimento>
         <tns:moedaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:currency_code"/>
         </tns:moedaLoja>
         <tns:linguagemLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:lang"/>
         </tns:linguagemLoja>
         <tns:possuiPOSIntegrado>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:integrated_pos_ind"/>
         </tns:possuiPOSIntegrado>
         <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns2:AddrDesc">
            <tns:DetalheEnderecoLojaList>
               <tns:tipoEndereco>
                  <xsl:value-of select="ns2:addr_type"/>
               </tns:tipoEndereco>
               <tns:enderecoPrimario>
                  <xsl:value-of select="ns2:primary_addr_ind"/>
               </tns:enderecoPrimario>
               <tns:cidade>
                  <xsl:value-of select="ns2:city"/>
               </tns:cidade>
               <tns:uf>
                  <xsl:value-of select="ns2:state"/>
               </tns:uf>
               <tns:cep>
                  <xsl:value-of select="ns2:post"/>
               </tns:cep>
            </tns:DetalheEnderecoLojaList>
         </xsl:for-each>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
