<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://service.ultra.com.br/logistica/AtualizacaoLojasRest/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/LegadoFault/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/StoreDesc/v1"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:Q4="http://canonico.ultra.com.br/LegadoOutput/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/AddrDesc/v1"
                xmlns:ns1="http://service.ultra.com.br/logistica/Lojas/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns5="http://www.oracle.com/retail/integration/custom/bo/ExtOfStoreDesc/v1"
                xmlns:ns6="http://www.oracle.com/retail/integration/base/bo/LocOfStoreDesc/v1"
                xmlns:ns4="http://www.oracle.com/retail/integration/localization/bo/BrFiscalStoreAttrDesc/v1"
                xmlns:ns8="http://www.oracle.com/retail/integration/base/bo/StoreRef/v1"
                xmlns:ns7="http://www.oracle.com/retail/integration/base/bo/AddrRef/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/Lojas/v1/WSDLs/LojasV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/AtualizacaoLojasRest.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://service.ultra.com.br/logistica/AtualizacaoLojasRest/v1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JUL 14 00:50:05 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:codigoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/*:StoreDesc/*:store" />
         </tns:codigoLoja>
         <tns:tipoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_type"/>
         </tns:tipoLoja>
         <tns:nomeLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name"/>
         </tns:nomeLoja>
         <tns:nomeFantasia>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name10"/>
         </tns:nomeFantasia>
         <tns:nomeAbreviado>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_name3"/>
         </tns:nomeAbreviado>
         <tns:enderecoPrincipal>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_add1"/>
         </tns:enderecoPrincipal>
         <tns:nomeCidade>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_city"/>
         </tns:nomeCidade>
         <tns:municipio>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:county"/>
         </tns:municipio>
         <tns:uf>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:state"/>
         </tns:uf>
         <tns:classeLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_class"/>
         </tns:classeLoja>
         <tns:gerentes>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_mgr_name"/>
         </tns:gerentes>
         <tns:dataAberturaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_open_date"/>
         </tns:dataAberturaLoja>
         <tns:dataFechamentoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:store_close_date"/>
         </tns:dataFechamentoLoja>
         <tns:telefoneLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:phone_number"/>
         </tns:telefoneLoja>
         <tns:emailLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:email"/>
         </tns:emailLoja>
         <tns:areaTotalLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:total_square_ft"/>
         </tns:areaTotalLoja>
         <tns:areaVendaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:selling_square_ft"/>
         </tns:areaVendaLoja>
         <tns:areaUtilizavelLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:linear_distance"/>
         </tns:areaUtilizavelLoja>
         <tns:lojaPossuiEstoque>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:stockholding_ind"/>
         </tns:lojaPossuiEstoque>
         <tns:codigoDistritoLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:district"/>
         </tns:codigoDistritoLoja>
         <tns:numeroDiasRecebimento>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:start_order_days"/>
         </tns:numeroDiasRecebimento>
         <tns:moedaLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:currency_code"/>
         </tns:moedaLoja>
         <tns:linguagemLoja>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:lang"/>
         </tns:linguagemLoja>
         <tns:possuiPOSIntegrado>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns3:integrated_pos_ind"/>
         </tns:possuiPOSIntegrado>
         <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns2:AddrDesc">
            <tns:DetalheEnderecoLojaList>
               <tns:idEndereco>
                  <xsl:value-of select="ns2:addr"/>
               </tns:idEndereco>
               <tns:tipoEndereco>
                  <xsl:value-of select="ns2:addr_type"/>
               </tns:tipoEndereco>
               <tns:enderecoPrimario>
                  <xsl:value-of select="ns2:primary_addr_ind"/>
               </tns:enderecoPrimario>
               <tns:cidade>
                  <xsl:value-of select="ns2:city"/>
               </tns:cidade>
               <tns:uf>
                  <xsl:value-of select="ns2:state"/>
               </tns:uf>
               <tns:cep>
                  <xsl:value-of select="ns2:post"/>
               </tns:cep>
            </tns:DetalheEnderecoLojaList>
         </xsl:for-each>
         <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns5:ExtOfStoreDesc">
            <tns:CustomizacaoCampoLojaList>
               <tns:remessaControlado>
                  <xsl:value-of select="ns5:controlled_shipping"/>
               </tns:remessaControlado>
               <tns:remessaRetinoico>
                  <xsl:value-of select="ns5:retinoic_shipping"/>
               </tns:remessaRetinoico>
               <tns:validadeLicencaRetinoico>
                  <xsl:value-of select="ns5:retinoic_lic_val"/>
               </tns:validadeLicencaRetinoico>
               <tns:numeroInscricaoSuframa>
                  <xsl:value-of select="ns5:suframa_num"/>
               </tns:numeroInscricaoSuframa>
               <tns:validadeSuframa>
                  <xsl:value-of select="ns5:suframa_val"/>
               </tns:validadeSuframa>
               <tns:registroLicencaVigilanciaSanitaria>
                  <xsl:value-of select="ns5:sanitary_lic_id"/>
               </tns:registroLicencaVigilanciaSanitaria>
               <tns:codigoAlvaraLocalizacaoPrefeitura>
                  <xsl:value-of select="ns5:alvara_loc_code"/>
               </tns:codigoAlvaraLocalizacaoPrefeitura>
               <tns:possuiAfeAnvisa>
                  <xsl:value-of select="ns5:afe_anvisa_ind"/>
               </tns:possuiAfeAnvisa>
               <tns:registroLicencaValidadeVigilanciaSanitaria>
                  <xsl:value-of select="ns5:lic_id_sanitary_val"/>
               </tns:registroLicencaValidadeVigilanciaSanitaria>
               <tns:enderecoFantasia>
                  <xsl:value-of select="ns5:fantasy_loc"/>
               </tns:enderecoFantasia>
               <tns:localizacaoCartesiana>
                  <xsl:value-of select="ns5:cartesian_loc"/>
               </tns:localizacaoCartesiana>
               <tns:gerenteDistrital>
                  <xsl:value-of select="ns5:district_manager"/>
               </tns:gerenteDistrital>
               <tns:gerenteMercado>
                  <xsl:value-of select="ns5:market_manager"/>
               </tns:gerenteMercado>
               <tns:horarioFuncionamento>
                  <xsl:value-of select="ns5:business_hours"/>
               </tns:horarioFuncionamento>
               <tns:tipoEstacionamento>
                  <xsl:value-of select="ns5:parking_type"/>
               </tns:tipoEstacionamento>
               <tns:lojaPolo>
                  <xsl:value-of select="ns5:polo_store_ind"/>
               </tns:lojaPolo>
               <tns:perfilSortimento>
                  <xsl:value-of select="ns5:assortment_profile"/>
               </tns:perfilSortimento>
               <tns:possuiTelefonia>
                  <xsl:value-of select="ns5:telephony_ind"/>
               </tns:possuiTelefonia>
               <tns:possuiFarmaciaPopular>
                  <xsl:value-of select="ns5:popular_drugstore_ind"/>
               </tns:possuiFarmaciaPopular>
               <tns:possuiServicosFarmaceutico>
                  <xsl:value-of select="ns5:pharm_services_ind"/>
               </tns:possuiServicosFarmaceutico>
               <tns:possuiCaixaEletronico>
                  <xsl:value-of select="ns5:cash_machine_ind"/>
               </tns:possuiCaixaEletronico>
               <tns:numeroTerminalAtendimento>
                  <xsl:value-of select="ns5:terminals_service"/>
               </tns:numeroTerminalAtendimento>
               <tns:numeroCheckout>
                  <xsl:value-of select="ns5:checkouts"/>
               </tns:numeroCheckout>
               <tns:numeroCestaoFralda>
                  <xsl:value-of select="ns5:diapers_basket"/>
               </tns:numeroCestaoFralda>
               <tns:numeroFreezer>
                  <xsl:value-of select="ns5:freezer_ind"/>
               </tns:numeroFreezer>
               <tns:numeroPontaGondola>
                  <xsl:value-of select="ns5:gondola_tips"/>
               </tns:numeroPontaGondola>
               <tns:numeroVagaEstacionamento>
                  <xsl:value-of select="ns5:parking_lots"/>
               </tns:numeroVagaEstacionamento>
               <tns:numeroGeladeira>
                  <xsl:value-of select="ns5:refrigerator_qty"/>
               </tns:numeroGeladeira>
               <tns:numeroCooler>
                  <xsl:value-of select="ns5:cooler_ind"/>
               </tns:numeroCooler>
               <tns:validadeVigilanciaSanitaria>
                  <xsl:value-of select="ns5:sanitary_val"/>
               </tns:validadeVigilanciaSanitaria>
               <tns:tamanhoLoja>
                  <xsl:value-of select="ns5:store_size"/>
               </tns:tamanhoLoja>
               <tns:areaTerreno>
                  <xsl:value-of select="ns5:land_area"/>
               </tns:areaTerreno>
               <tns:areaConstruida>
                  <xsl:value-of select="ns5:building_area"/>
               </tns:areaConstruida>
               <tns:areaVendas>
                  <xsl:value-of select="ns5:sales_area"/>
               </tns:areaVendas>
               <tns:padraoArquitetonico>
                  <xsl:value-of select="ns5:arch_standard"/>
               </tns:padraoArquitetonico>
               <tns:clusterVenda>
                  <xsl:value-of select="ns5:cluster_sales"/>
               </tns:clusterVenda>
               <tns:tipoLoja>
                  <xsl:value-of select="ns5:store_type"/>
               </tns:tipoLoja>
               <tns:totem>
                  <xsl:value-of select="ns5:totem_ind"/>
               </tns:totem>
               <tns:idLojaFisica>
                  <xsl:value-of select="ns5:id_phys_store"/>
               </tns:idLojaFisica>
            </tns:CustomizacaoCampoLojaList>
         </xsl:for-each>
         <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns3:StoreDesc/ns6:LocOfStoreDesc">
            <tns:CustomizacaoCampoFiscalList>
               <xsl:for-each select="ns4:BrFiscalStoreAttrDesc">
                  <tns:CampoFiscalList>
                     <tns:bairroLoja>
                        <xsl:value-of select="ns4:neighborhood"/>
                     </tns:bairroLoja>
                     <tns:inscricaoEstadual>
                        <xsl:value-of select="ns4:state_registration"/>
                     </tns:inscricaoEstadual>
                     <tns:cnpj>
                        <xsl:value-of select="ns4:cnpj"/>
                     </tns:cnpj>
                  </tns:CampoFiscalList>
               </xsl:for-each>
            </tns:CustomizacaoCampoFiscalList>
         </xsl:for-each>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
