<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://service.ultra.com.br/fiscal/NFSaidaMercadoria/v1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1"
                xmlns:Q5="http://canonico.ultra.com.br/LegadoFault/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:Q4="http://canonico.ultra.com.br/LegadoOutput/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/EXFItemDesc/v1"
                xmlns:ns1="http://www.oracle.com/retail/integration/custom/bo/ExtOfShipInfoDesc/v1"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/ShipInfoDesc/v1"
                xmlns:ns5="http://www.oracle.com/retail/integration/base/bo/SODesc/v1"
                xmlns:ns4="http://www.oracle.com/retail/integration/custom/bo/ExtOfSODesc/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/NFSaidaMercadoria/v1/WSDLs/NFSaidaMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CriarNFSaidaMercadoriaRequest" namespace="http://service.ultra.com.br/fiscal/NFSaidaMercadoria/v1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/NFSaidaMercadoria/v1/WSDLs/NFSaidaMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JUL 27 15:56:12 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RibMessages>
         <tns:ribMessage>
            <tns:family>shipinfo</tns:family>
            <tns:type>shipinfocre</tns:type>
            <tns:id>
               <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:identificacaoTransferencia"/>
            </tns:id>
            <tns:routingInfo>
               <tns:name>from_phys_loc</tns:name>
               <tns:value>
                  <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:tipoLocalOrigem"/>
               </tns:value>
            </tns:routingInfo>
            <tns:routingInfo>
               <tns:name>to_phys_loc</tns:name>
               <tns:value>
                  <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:tipoLocalDestino"/>
               </tns:value>
            </tns:routingInfo>
            <tns:publishTime>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:publishTime>
            <tns:messageData>
               <ns3:ShipInfoDesc>
                  <ns3:to_loc_type>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:codigoLocalDestino"/>
                  </ns3:to_loc_type>
                  <ns3:to_location>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:tipoLocalDestino"/>
                  </ns3:to_location>
                  <ns3:from_loc_type>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:codigoLocalOrigem"/>
                  </ns3:from_loc_type>
                  <ns3:from_location>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:tipoLocalOrigem"/>
                  </ns3:from_location>
                  <ns3:asn_nbr>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:numeroPedidoCliente"/>
                  </ns3:asn_nbr>
                  <ns3:asn_type>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:tipoPedidoTransferencia"/>
                  </ns3:asn_type>
                  <ns3:container_qty>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:quantidadeCaixasPedido"/>
                  </ns3:container_qty>
                  <ns3:bol_nbr>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:identificacaoTransferencia"/>
                  </ns3:bol_nbr>
                  <ns3:shipment_date>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:dataTransferencia"/>
                  </ns3:shipment_date>
                  <ns3:carrier_code>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:codigoIdentificacaoTransportadora"/>
                  </ns3:carrier_code>
                  <ns3:carrier_service_code>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:codigoNivelServicoTransportadora"/>
                  </ns3:carrier_service_code>
                  <ns3:printer_id>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:codigoIdentificacaoImpressora"/>
                  </ns3:printer_id>
                  <ns3:print_pkg_stn_req>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:IdentificacaoImpressaoRequerida"/>
                  </ns3:print_pkg_stn_req>
                  <ns3:home_dlvry_ind>
                     <xsl:value-of select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:IdentificacaiEntregaDomicilio"/>
                  </ns3:home_dlvry_ind>
                  <xsl:for-each select="/ns0:CriarNFSaidaMercadoriaRequest/ns0:NFSaidaDetalheList">
                     <ns3:ShipInfoDistro>
                        <xsl:for-each select="ns0:CaixasNotaFiscalSaidaList">
                           <ns3:ShipInfoCtn>
                              <xsl:for-each select="ns0:ItemNotaFiscalSaidaList">
                                 <ns3:ShipInfoItem/>
                              </xsl:for-each>
                           </ns3:ShipInfoCtn>
                        </xsl:for-each>
                     </ns3:ShipInfoDistro>
                  </xsl:for-each>
               </ns3:ShipInfoDesc>
            </tns:messageData>
            <tns:customFlag>F</tns:customFlag>
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
