<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://service.ultra.com.br/fiscal/PublicacaoNFSaidaMercadoriaRest/v1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:Q4="http://schemas.datacontract.org/2004/07/Wsdl.Integration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://service.ultra.com.br/fiscal/NFSaidaMercadoria/v1"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/EXFItemDesc/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/EXFBrInvoicesDesc/v1"
                xmlns:Q5="http://canonico.ultra.com.br/LegadoFault/v1"
                xmlns:ns4="http://canonico.ultra.com.br/LegadoOutput/v1"
                xmlns:ns5="http://www.oracle.com/retail/integration/custom/bo/ExtOfSODesc/v1"
                xmlns:ns6="http://www.oracle.com/retail/integration/base/bo/SODesc/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/NFSaidaMercadoria/v1/WSDLs/NFSaidaMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PublicacaoNFSaidaMercadoriaRest.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://service.ultra.com.br/fiscal/PublicacaoNFSaidaMercadoriaRest/v1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON JUL 10 13:05:40 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:codigoAgrupador>
            <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns2:EXFBrInvoicesDesc/ns2:ref_no"/>
         </tns:codigoAgrupador>
         <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns2:EXFBrInvoicesDesc/ns2:EXFNFInfoDesc">
            <tns:NotaFiscalList>
               <tns:contadorNotaFiscal>
                  <xsl:value-of select="ns2:nf_line_no"/>
               </tns:contadorNotaFiscal>
               <tns:numeroNotaFiscal>
                  <xsl:value-of select="ns2:fiscal_doc_no"/>
               </tns:numeroNotaFiscal>
               <tns:numeroSerie>
                  <xsl:value-of select="ns2:series_no"/>
               </tns:numeroSerie>
               <tns:codigoFilial>
                  <xsl:value-of select="ns2:location_id"/>
               </tns:codigoFilial>
               <tns:cnpjEmissor>
                  <xsl:value-of select="ns2:issue_cnpj"/>
               </tns:cnpjEmissor>
               <tns:dataEmissao>
                  <xsl:value-of select="ns2:issue_date"/>
               </tns:dataEmissao>
               <tns:cfopPrincipal>
                  <xsl:value-of select="ns2:nf_cfop"/>
               </tns:cfopPrincipal>
               <tns:codigoCliente>
                  <xsl:value-of select="ns2:key_value_1"/>
               </tns:codigoCliente>
               <tns:pesoLiquido>
                  <xsl:value-of select="ns2:net_weight"/>
               </tns:pesoLiquido>
               <tns:pesoBruto>
                  <xsl:value-of select="ns2:total_weight"/>
               </tns:pesoBruto>
               <tns:totalDesconto>
                  <xsl:value-of select="ns2:total_discount_value"/>
               </tns:totalDesconto>
               <tns:totalBrunoNotaFiscal>
                  <xsl:value-of select="ns2:total_item_value"/>
               </tns:totalBrunoNotaFiscal>
               <tns:totalNotaFiscal>
                  <xsl:value-of select="ns2:total_doc_value"/>
               </tns:totalNotaFiscal>
               <tns:codigoImpressora>
                  <xsl:value-of select="ns2:printer_id"/>
               </tns:codigoImpressora>
               <tns:chaveAcessoNotaFiscal>
                  <xsl:value-of select="ns2:nfe_access_key"/>
               </tns:chaveAcessoNotaFiscal>
               <tns:protocoloAutorizacao>
                  <xsl:value-of select="ns2:nfe_protocol"/>
               </tns:protocoloAutorizacao>
               <xsl:for-each select="ns2:EXFNFInfoDtl">
                  <tns:ProdutoNotaFiscalList>
                     <tns:item>
                        <xsl:value-of select="ns2:line_no"/>
                     </tns:item>
                     <tns:numeroPedido>
                        <xsl:value-of select="ns2:requisition_no"/>
                     </tns:numeroPedido>
                     <tns:codigoProduto>
                        <xsl:value-of select="ns2:item"/>
                     </tns:codigoProduto>
                     <tns:quantidadeAtendida>
                        <xsl:value-of select="ns2:quantity"/>
                     </tns:quantidadeAtendida>
                     <tns:precoSemImposto>
                        <xsl:value-of select="ns2:unit_cost_with_desc"/>
                     </tns:precoSemImposto>
                     <tns:precoFinalProduto>
                        <xsl:value-of select="ns2:total_cost"/>
                     </tns:precoFinalProduto>
                     <tns:cfopItem>
                        <xsl:value-of select="ns2:ref_doc_no"/>
                     </tns:cfopItem>
                     <xsl:for-each select="ns3:EXFLotInfoDesc">
                        <tns:LoteProdutoList>
                           <tns:lote>
                              <xsl:value-of select="ns3:lot_id"/>
                           </tns:lote>
                           <tns:dataFabricacao>
                              <xsl:value-of select="ns3:manufacture_date"/>
                           </tns:dataFabricacao>
                           <tns:dataValidade>
                              <xsl:value-of select="ns3:expiration_date"/>
                           </tns:dataValidade>
                           <tns:quantidade>
                              <xsl:value-of select="ns3:lot_qty"/>
                           </tns:quantidade>
                        </tns:LoteProdutoList>
                     </xsl:for-each>
                  </tns:ProdutoNotaFiscalList>
               </xsl:for-each>
            </tns:NotaFiscalList>
         </xsl:for-each>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
