<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="NFEntradaMercadoria"
     targetNamespace="http://extrafarma/fiscal/v1/nf/publicacaoNFEntrada/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://extrafarma/fiscal/v1/nf/publicacaoNFEntrada/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="NFEntradaMercadoriaDBBPEL">
        <plnk:role name="NFEntradaMercadoriaPortType" portType="tns:NFEntradaMercadoriaPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://extrafarma/fiscal/v1/nf/publicacaoNFEntrada/v1" location="oramds:/apps/Extrafarma/Retail/NFEntradaMercadoria/v1/WSDLs/NFEntradaMercadoriaV1.wsdl"/>
</wsdl:definitions>
