<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://service.ultra.com.br/logistica/PedidoTransferenciaMercadoria/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1"
                xmlns:ns1="http://service.ultra.com.br/logistica/PedidoTransferenciaMercadoriaDet/v1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/PedidoTransferenciaMercadoriaIntegracaoBPEL/etSOStatusReference"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/SOStatusDesc/v1" xml:id="id_1"
                oraxsl:ignorexmlids="true">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/PedidoTransferenciaMercadoriaV1.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="PedidoTransferenciaMercadoriaRequest" namespace="http://service.ultra.com.br/logistica/PedidoTransferenciaMercadoria/v1"
                                           xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/etSOStatusJMSReference.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"
                                           xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE JUN 27 14:18:07 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:RibMessages xml:id="id_12">
         <tns:ribMessage xml:id="id_13">
            <tns:family xml:id="id_14">soastatus</tns:family>
            <tns:type xml:id="id_15">sostatuscre</tns:type>
            <tns:id xml:id="id_16">
               <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/numeroPedido" xml:id="id_17"/>
            </tns:id>
            <tns:ribmessageID xml:id="id_18">
               <xsl:value-of select="concat (dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '067', 'family', ''), '|', xp20:current-dateTime(),'|', /ns0:PedidoTransferenciaMercadoriaRequest/numeroPedido)"
                             xml:id="id_19"/>
            </tns:ribmessageID>
            <tns:publishTime xml:id="id_20">
               <xsl:value-of select="xp20:current-dateTime ( )" xml:id="id_21"/>
            </tns:publishTime>
            <tns:messageData xml:id="id_55">
               <ns3:SOStatusDesc xml:id="id_56">
                  <ns3:dc_dest_id xml:id="id_57">
                     <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/codigoLocalOrigem" xml:id="id_58"/>
                  </ns3:dc_dest_id>
                  <ns3:loc_type xml:id="id_68">
                     <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/tipoLocal" xml:id="id_69"/>
                  </ns3:loc_type>
                  <ns3:store_type xml:id="id_66">
                     <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/tipoLoja" xml:id="id_67"/>
                  </ns3:store_type>
                  <ns3:stockholding_ind xml:id="id_64"/>
                  <ns3:distro_nbr xml:id="id_59">
                     <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/numeroPedido" xml:id="id_63"/>
                  </ns3:distro_nbr>
                  <ns3:distro_document_type xml:id="id_61">
                     <xsl:value-of select="/ns0:PedidoTransferenciaMercadoriaRequest/statusOrdemEstoque"
                                   xml:id="id_62"/>
                  </ns3:distro_document_type>
                  <xsl:for-each xml:id="id_70"
                                select="/ns0:PedidoTransferenciaMercadoriaRequest/PedidoTransferenciaMercadoriaDetalhe">
                     <ns3:SOStatusDtl xml:id="id_71">
                        <ns3:dest_id xml:id="id_72">
                           <xsl:value-of select="codigoLocalRecebimento" xml:id="id_73"/>
                        </ns3:dest_id>
                        <ns3:loc_type xml:id="id_74">
                           <xsl:value-of select="tipoLocal" xml:id="id_75"/>
                        </ns3:loc_type>
                        <ns3:store_type xml:id="id_76">
                           <xsl:value-of select="tipoLoja" xml:id="id_77"/>
                        </ns3:store_type>
                        <ns3:item_id xml:id="id_78">
                           <xsl:value-of select="codigoItem" xml:id="id_79"/>
                        </ns3:item_id>
                        <ns3:order_line_nbr xml:id="id_80">
                           <xsl:value-of select="numeroLinha" xml:id="id_81"/>
                        </ns3:order_line_nbr>
                        <ns3:unit_qty xml:id="id_82">
                           <xsl:value-of select="quantidadeItem" xml:id="id_83"/>
                        </ns3:unit_qty>
                        <ns3:status xml:id="id_84">
                           <xsl:value-of select="statusEstoque" xml:id="id_85"/>
                        </ns3:status>
                     </ns3:SOStatusDtl>
                  </xsl:for-each>
               </ns3:SOStatusDesc>
            </tns:messageData>
            <tns:customFlag xml:id="id_52">
            </tns:customFlag>
             <tns:customFlag xml:id="id_53">
               <xsl:value-of select="oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '067', 'customFlag', '')"
                             xml:id="id_54"/>
            </tns:customFlag>
            
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
