<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="NotaFiscalSaidaMercadoria"
     targetNamespace="http://xmlns.oracle.com/AppExtrafarmaServiceBUS/NotaFiscalSaidaMercadoriaIntegracaoServico/NotaFiscalSaidaMercadoria"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/AppExtrafarmaServiceBUS/NotaFiscalSaidaMercadoriaIntegracaoServico/NotaFiscalSaidaMercadoria"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="NotaFiscalSaidaDBBPEL1">
        <plnk:role name="NotaFiscalSaidaMercadoriaPortType" portType="tns:NotaFiscalSaidaMercadoriaPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://service.ultra.com.br/logistica/DevolucaoMercadoria/v1" location="NotaFiscalSaidaMercadoriaV1.wsdl"/>
</wsdl:definitions>
