<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="NFEntradaMercadoria"
     targetNamespace="http://service.ultra.com.br/fiscal/NFEntradaMercadoria/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://service.ultra.com.br/fiscal/NFEntradaMercadoria/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://TargetNamespace.com/nxsdschema"
    >
    <plnk:partnerLinkType name="NFEntradaMercadoriaDBBPEL">
        <plnk:role name="NFEntradaMercadoriaPortType" portType="tns:NFEntradaMercadoriaPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://service.ultra.com.br/fiscal/NFEntradaMercadoria/v1" location="NFEntradaMercadoriaV1.wsdl"/>
</wsdl:definitions>
