<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://service.ultra.com.br/logistica/DevolucaoMercadoria/v1" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/EXFItemDesc/v1"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns4="http://www.oracle.com/retail/integration/custom/bo/ExtOfRTVDesc/v1"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/RTVDesc/v1"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/DevolucaoMercadoriaIntegracaoBPEL/EtRTVJMSReference">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DevolucaoMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="NotificarDevolucaoMercadoriaRequest" namespace="http://service.ultra.com.br/logistica/DevolucaoMercadoria/v1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EtRTVJMSReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED JUN 21 18:45:51 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RibMessages>
         <tns:ribMessage>
         <tns:family>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '063', 'family', '')"/>
         </tns:family>
         <tns:type>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '063', 'type', '')"/>
         </tns:type>
         <tns:messageData>
            <ns3:RTVDesc>
               <ns3:dc_dest_id>
                  <xsl:value-of select="string(/ns0:NotificarDevolucaoMercadoriaRequest/codigoFilial)"/>
               </ns3:dc_dest_id>
               <ns3:rtv_id>
                  <xsl:value-of select="string(/ns0:NotificarDevolucaoMercadoriaRequest/numeroPedido)"/>
               </ns3:rtv_id>
               <ns3:vendor_nbr>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/codigoFornecedor"/>
               </ns3:vendor_nbr>
               <ns3:ship_address1>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/endereco1"/>
               </ns3:ship_address1>
               <ns3:ship_address2>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/endereco2"/>
               </ns3:ship_address2>
               <ns3:ship_address3>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/endereco3"/>
               </ns3:ship_address3>
               <ns3:state>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/estado"/>
               </ns3:state>
               <ns3:city>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/cidade"/>
               </ns3:city>
               <ns3:shipto_zip>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/cep"/>
               </ns3:shipto_zip>
               <ns3:creation_ts>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/dataCriacao"/>
               </ns3:creation_ts>
               <ns3:comments>
                  <xsl:value-of select="string(/ns0:NotificarDevolucaoMercadoriaRequest/comentarios)"/>
               </ns3:comments>
               <ns3:rtv_order_no>
                  <xsl:value-of select="/ns0:NotificarDevolucaoMercadoriaRequest/numeroPedidoFornecedor"/>
               </ns3:rtv_order_no>
               <xsl:for-each select="/ns0:NotificarDevolucaoMercadoriaRequest/DevolucaoDetalheList">
                  <ns3:RTVDtl>
                     <ns3:item_id>
                        <xsl:value-of select="string(codigoProduto)"/>
                     </ns3:item_id>
                     <ns3:unit_qty>
                        <xsl:value-of select="format-number(quantidadeDevolucao,'############.0000')"/>
                     </ns3:unit_qty>
                     <ns3:from_disposition>
                        <xsl:value-of select="statusInventario"/>
                     </ns3:from_disposition>
                     <xsl:for-each select="ItemList">
                        <ns4:ExtOfRTVDtl>
                           <xsl:for-each select="LoteItemList">
                              <ns2:EXFItemDtl>
                                 <ns2:volume>
                                    <xsl:value-of select="string(codigoVolumeProduto)"/>
                                 </ns2:volume>
                                 <xsl:for-each select="LoteItemDetalheList">
                                    <ns2:EXFLotInfoDesc>
                                       <ns2:lot_id>
                                          <xsl:value-of select="codigoLote"/>
                                       </ns2:lot_id>
                                       <ns2:expiration_date>
                                          <xsl:value-of select="dataValidade"/>
                                       </ns2:expiration_date>
                                       <ns2:lot_qty>
                                          <xsl:value-of select="format-number(quantidadeLote,'############.0000')"/>
                                       </ns2:lot_qty>
                                    </ns2:EXFLotInfoDesc>
                                 </xsl:for-each>
                              </ns2:EXFItemDtl>
                           </xsl:for-each>
                        </ns4:ExtOfRTVDtl>
                     </xsl:for-each>
                  </ns3:RTVDtl>
               </xsl:for-each>
               <xsl:for-each select="/ns0:NotificarDevolucaoMercadoriaRequest/InformacoesAdicionaisList">
                  <ns4:ExtOfRTVDesc>
                     <ns4:carrier_code>
                        <xsl:value-of select="codigoTransportadora"/>
                     </ns4:carrier_code>
                  </ns4:ExtOfRTVDesc>
               </xsl:for-each>
            </ns3:RTVDesc>
         </tns:messageData>
         <tns:customFlag>
            <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '063', 'customFlag', '')"/>
         </tns:customFlag>
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
