<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:tns="http://extrafarma/fiscal/v1/nf/publicacaoNFEntrada/v1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1"
                xmlns:ns1="http://www.oracle.com/retail/integration/base/bo/EXFNFInfoDesc/v1"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/EXFItemDesc/v1"
                xmlns:Q4="http://schemas.datacontract.org/2004/07/Wsdl.Integration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/ASNOutDesc/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns4="http://www.oracle.com/retail/integration/custom/bo/ExtOfASNOutDesc/v1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns7="http://canonico.ultra.com.br/LegadoOutput/v1"
                xmlns:ns6="http://canonico.ultra.com.br/LegadoFault/v1"
                xmlns:ns5="http://service.ultra.com.br/fiscal/NFEntradaMercadoria/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/NFEntradaMercadoria/v1/WSDLs/NFEntradaMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NFEntradaMercadoriaJson.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://extrafarma/fiscal/v1/nf/publicacaoNFEntrada/v1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE JUL 11 21:33:35 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:InformacaoNotaFiscal>
            <xsl:for-each select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/ns2:ASNOutDesc/ns4:ExtOfASNOutDesc/ns1:EXFNFInfoDesc">
               <tns:NotaFiscal>
                  <tns:numeroNotaFiscal>
                     <xsl:value-of select="ns1:fiscal_doc_no"/>
                  </tns:numeroNotaFiscal>
                  <tns:numeroSerieNotaFiscal>
                     <xsl:value-of select="ns1:series_no"/>
                  </tns:numeroSerieNotaFiscal>
                  <tns:cnpjEmissor>
                     <xsl:value-of select="ns1:issue_cnpj"/>
                  </tns:cnpjEmissor>
                  <tns:dataEmissaoNotaFiscal>
                     <xsl:value-of select="ns1:issue_date"/>
                  </tns:dataEmissaoNotaFiscal>
                  <tns:chaveAcessoNotaFiscal>
                     <xsl:value-of select="ns1:nfe_access_key"/>
                  </tns:chaveAcessoNotaFiscal>
                  <tns:codigoDestino>
                     <xsl:value-of select="ns1:location_id"/>
                  </tns:codigoDestino>
                  <tns:valorTotalNotaFiscal>
                     <xsl:value-of select="ns1:total_doc_value"/>
                  </tns:valorTotalNotaFiscal>
                  <xsl:for-each select="ns1:EXFNFInfoDtl">
                     <tns:ProdutoList>
                        <tns:codigoProduto>
                           <xsl:value-of select="ns1:item"/>
                        </tns:codigoProduto>
                        <tns:quantidade>
                           <xsl:value-of select="ns1:quantity"/>
                        </tns:quantidade>
                        <xsl:for-each select="ns3:EXFLotInfoDesc">
                           <tns:LoteList>
                              <tns:loteProduto>
                                 <xsl:value-of select="ns3:lot_id"/>
                              </tns:loteProduto>
                              <tns:dataFabricacao>
                                 <xsl:value-of select="ns3:manufacture_date"/>
                              </tns:dataFabricacao>
                              <tns:dataValidade>
                                 <xsl:value-of select="ns3:expiration_date"/>
                              </tns:dataValidade>
                              <tns:quantidadeLote>
                                 <xsl:value-of select="ns3:lot_qty"/>
                              </tns:quantidadeLote>
                           </tns:LoteList>
                        </xsl:for-each>
                     </tns:ProdutoList>
                  </xsl:for-each>
               </tns:NotaFiscal>
            </xsl:for-each>
         </tns:InformacaoNotaFiscal>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
