<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="RecebimentoNFCompra"
     targetNamespace="http://service.ultra.com.br/logistica/RecebimentoNFCompra/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://service.ultra.com.br/logistica/RecebimentoNFCompra/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="RecebimentoNFCompraV1DReference">
        <plnk:role name="RecebimentoNFCompraPortType" portType="tns:RecebimentoNFCompraPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://service.ultra.com.br/logistica/RecebimentoNFCompra/v1" location="oramds:/apps/Extrafarma/Retail/Comum/v1/ServicesRetail/RecebimentoNFCompra/WSDLs/RecebimentoNFCompraV1.wsdl"/>
</wsdl:definitions>
