<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://service.ultra.com.br/atacado/PedidoReserva/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://TargetNamespace.com/nxsdschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns1="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmDtl/v1"
                xmlns:rib="http://www.oracle.com/retail/integration/rib/RibMessages"
                xmlns:Q4="http://schemas.datacontract.org/2004/07/Wsdl.Integration"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmDesc/v1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/PedidoReserva/WSDLs/PedidoReservaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_schema1.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/nxsdschema"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SUN JUL 02 21:36:37 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:PedidoList>
            <xsl:for-each select="/ns0:ConfirmarPedidoReservaRequest/ConfirmaOrdemClienteList">
               <tns:numeroPedido>
                  <xsl:value-of select="ns0:codigoPedidoCliente"/>
               </tns:numeroPedido>
            </xsl:for-each>
            <tns:numeroOrdemAtendimento>
               <xsl:value-of select="/ns0:ConfirmarPedidoReservaRequest/ConfirmaOrdemClienteList/ns0:codigoOrdemAtendimentoConfirmado"/>
            </tns:numeroOrdemAtendimento>
            <tns:tipoConfirmacao>
               <xsl:value-of select="/ns0:ConfirmarPedidoReservaRequest/ConfirmaOrdemClienteList/ns0:tipoConfirmado"/>
            </tns:tipoConfirmacao>
            <tns:numeroPedidoConfirmacao>
               <xsl:value-of select="/ns0:ConfirmarPedidoReservaRequest/ConfirmaOrdemClienteList/ns0:codigoAssociadoConfirmadoTransferencia"/>
            </tns:numeroPedidoConfirmacao>
            <xsl:for-each select="/ns0:ConfirmarPedidoReservaRequest/ConfirmaOrdemClienteList/ns0:ConfirmaOrdemDetalheList">
               <tns:ItemPedidoList>
                  <tns:itemConfirmado>
                     <xsl:value-of select="codigoItem"/>
                  </tns:itemConfirmado>
                  <tns:codigoProduto>
                     <xsl:value-of select="upcItem"/>
                  </tns:codigoProduto>
                  <tns:quantidadeAtendida>
                     <xsl:value-of select="quantidadeConfirmadaItem"/>
                  </tns:quantidadeAtendida>
                  <tns:unidadeMedida>
                     <xsl:value-of select="unidadeMedidaConfirmada"/>
                  </tns:unidadeMedida>
               </tns:ItemPedidoList>
            </xsl:for-each>
         </tns:PedidoList>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
