<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://service.ultra.com.br/atacado/PedidoReserva/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q4="http://schemas.datacontract.org/2004/07/Wsdl.Integration"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/LocOfFulfilOrdCustDesc/v1"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:ns3="http://www.oracle.com/retail/integration/localization/bo/BrFulfilOrdPmtDesc/v1"
                xmlns:ns6="http://www.oracle.com/retail/integration/localization/bo/BrFulfilOrdCustDesc/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns7="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDesc/v1"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1"
                xmlns:ns1="http://www.oracle.com/retail/integration/custom/bo/EOfBrFulfilOrdPmtDesc/v1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns4="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDtl/v1"
                xmlns:ns5="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCustDesc/v1"
                xmlns:ns8="http://www.oracle.com/retail/integration/custom/bo/EOfBrFulfilOrdCustDesc/v1"
                xmlns:ns9="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDtlRef/v1"
                xmlns:ns10="http://www.oracle.com/retail/integration/base/bo/FulfilOrdRef/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/PedidoReserva/v1/WSDLs/PedidoReservaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CriarPedidoReservaRequest" namespace="http://service.ultra.com.br/atacado/PedidoReserva/v1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/PedidoReserva/v1/WSDLs/PedidoReservaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 06 01:32:10 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RibMessages>
         <tns:ribMessage>
            <tns:family>
               <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '035', 'family', '')"/>
            </tns:family>
            <tns:type>
               <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '035', 'type', '')"/>
            </tns:type>
            <tns:messageData>
               <ns7:FulfilOrdDesc>
                  <ns7:customer_order_no>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/codigoPedidoCliente"/>
                  </ns7:customer_order_no>
                  <ns7:fulfill_order_no>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/codigoPedidoAtendimento"/>
                  </ns7:fulfill_order_no>
                  <ns7:source_loc_type>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/tipoLocalOrigem"/>
                  </ns7:source_loc_type>
                  <ns7:source_loc_id>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/localOrigem"/>
                  </ns7:source_loc_id>
                  <ns7:fulfill_loc_type>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/tipoLocalDestino"/>
                  </ns7:fulfill_loc_type>
                  <ns7:fulfill_loc_id>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/localDestino"/>
                  </ns7:fulfill_loc_id>
                  <ns7:partial_delivery_ind>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/flagPodeSerAtendimentaParcialmente"/>
                  </ns7:partial_delivery_ind>
                  <ns7:delivery_type>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/tipoEntrega"/>
                  </ns7:delivery_type>
                  <ns7:consumer_delivery_date>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/dataPrevisaoChegada"/>
                  </ns7:consumer_delivery_date>
                  <ns7:comments>
                     <xsl:value-of select="/ns0:CriarPedidoReservaRequest/comentario"/>
                  </ns7:comments>
                  <xsl:for-each select="/ns0:CriarPedidoReservaRequest/OrdemCliente">
                     <ns5:FulfilOrdCustDesc>
                        <ns5:customer_no>
                           <xsl:value-of select="ns0:numeroOrdemOms"/>
                        </ns5:customer_no>
                        <ns5:deliver_first_name>
                           <xsl:value-of select="ns0:primeiroNomeCliente"/>
                        </ns5:deliver_first_name>
                        <ns5:deliver_phonetic_first>
                           <xsl:value-of select="ns0:nomeFoneticoCliente"/>
                        </ns5:deliver_phonetic_first>
                        <ns5:deliver_last_name>
                           <xsl:value-of select="ns0:sobrenomeCliente"/>
                        </ns5:deliver_last_name>
                        <ns5:deliver_phonetic_last>
                           <xsl:value-of select="ns0:sobrenomeFoneticoCliente"/>
                        </ns5:deliver_phonetic_last>
                        <ns5:deliver_preferred_name>
                           <xsl:value-of select="ns0:nomePreferivelEntrega"/>
                        </ns5:deliver_preferred_name>
                        <ns5:deliver_company_name>
                           <xsl:value-of select="ns0:nomeCompanhiaCliente"/>
                        </ns5:deliver_company_name>
                        <ns5:deliver_add1>
                           <xsl:value-of select="ns0:endereco1"/>
                        </ns5:deliver_add1>
                        <ns5:deliver_add2>
                           <xsl:value-of select="ns0:endereco2"/>
                        </ns5:deliver_add2>
                        <ns5:deliver_add3>
                           <xsl:value-of select="ns0:endereco3"/>
                        </ns5:deliver_add3>
                        <ns5:deliver_county>
                           <xsl:value-of select="ns0:municipio"/>
                        </ns5:deliver_county>
                        <ns5:deliver_city>
                           <xsl:value-of select="ns0:cidade"/>
                        </ns5:deliver_city>
                        <ns5:deliver_state>
                           <xsl:value-of select="ns0:estado"/>
                        </ns5:deliver_state>
                        <ns5:deliver_country_id>
                           <xsl:value-of select="ns0:pais"/>
                        </ns5:deliver_country_id>
                        <ns5:deliver_post>
                           <xsl:value-of select="ns0:cepLocalEntrega"/>
                        </ns5:deliver_post>
                        <ns5:deliver_jurisdiction>
                           <xsl:value-of select="ns0:codigoJurisdicaoLocalEntrega"/>
                        </ns5:deliver_jurisdiction>
                        <ns5:deliver_phone>
                           <xsl:value-of select="ns0:telefoneCliente"/>
                        </ns5:deliver_phone>
                        <ns5:deliver_email>
                           <xsl:value-of select="ns0:emailCliente"/>
                        </ns5:deliver_email>
                        <ns5:bill_first_name>
                           <xsl:value-of select="ns0:nomeClienteCobranca"/>
                        </ns5:bill_first_name>
                        <ns5:bill_phonetic_first>
                           <xsl:value-of select="ns0:primeiroNomeFoneticoCliente"/>
                        </ns5:bill_phonetic_first>
                        <ns5:bill_last_name>
                           <xsl:value-of select="ns0:sobrenomeClienteCobranca"/>
                        </ns5:bill_last_name>
                        <ns5:bill_phonetic_last>
                           <xsl:value-of select="ns0:ultimoNomeClienteCobranca"/>
                        </ns5:bill_phonetic_last>
                        <ns5:bill_preferred_name>
                           <xsl:value-of select="ns0:nomePreferivelClienteCobranca"/>
                        </ns5:bill_preferred_name>
                        <ns5:bill_company_name>
                           <xsl:value-of select="ns0:nomeEmpresaCobranca"/>
                        </ns5:bill_company_name>
                        <ns5:bill_add1>
                           <xsl:value-of select="ns0:enderecoCobranca1"/>
                        </ns5:bill_add1>
                        <ns5:bill_add2>
                           <xsl:value-of select="ns0:enderecoCobranca2"/>
                        </ns5:bill_add2>
                        <ns5:bill_add3>
                           <xsl:value-of select="ns0:enderecoCobranca3"/>
                        </ns5:bill_add3>
                        <ns5:bill_county>
                           <xsl:value-of select="ns0:municipioCobranca"/>
                        </ns5:bill_county>
                        <ns5:bill_city>
                           <xsl:value-of select="ns0:cidadeCobranca"/>
                        </ns5:bill_city>
                        <ns5:bill_state>
                           <xsl:value-of select="ns0:estadoCobranca"/>
                        </ns5:bill_state>
                        <ns5:bill_country_id>
                           <xsl:value-of select="ns0:paisCobranca"/>
                        </ns5:bill_country_id>
                        <ns5:bill_post>
                           <xsl:value-of select="ns0:cepCobranca"/>
                        </ns5:bill_post>
                        <ns5:bill_jurisdiction>
                           <xsl:value-of select="ns0:codigoJurisdicaoCobranca"/>
                        </ns5:bill_jurisdiction>
                        <ns5:bill_phone>
                           <xsl:value-of select="ns0:telefoneCobranca"/>
                        </ns5:bill_phone>
                        <ns5:bill_email>
                           <xsl:value-of select="ns0:emailCobranca"/>
                        </ns5:bill_email>
                        <xsl:for-each select="ns0:DadoFiscalCliente">
                           <ns2:LocOfFulfilOrdCustDesc>
                              <xsl:for-each select="DadosFiscaisDetalheList">
                                 <ns6:BrFulfilOrdCustDesc>
                                    <ns6:cpf>
                                       <xsl:value-of select="cpf"/>
                                    </ns6:cpf>
                                    <ns6:neighborhood>
                                       <xsl:value-of select="bairroCliente"/>
                                    </ns6:neighborhood>
                                    <ns6:ie_exempt>
                                       <xsl:value-of select="isentoInscricaoEstadual"/>
                                    </ns6:ie_exempt>
                                    <ns6:presence_ind>
                                       <xsl:value-of select="entregaPresencial"/>
                                    </ns6:presence_ind>
                                    <ns6:taxpayer_type>
                                       <xsl:value-of select="tipoPessoa"/>
                                    </ns6:taxpayer_type>
                                    <ns6:fiscal_address_information>
                                       <xsl:value-of select="enderecoFiscal"/>
                                    </ns6:fiscal_address_information>
                                    <ns6:individual_taxpayer_id>
                                       <xsl:value-of select="cpfCliente"/>
                                    </ns6:individual_taxpayer_id>
                                    <ns6:corporate_taxpayer_id>
                                       <xsl:value-of select="cnpjCliente"/>
                                    </ns6:corporate_taxpayer_id>
                                    <ns6:free_zone_of_manaus_inscptn_id>
                                       <xsl:value-of select="codigoSuframaCliente"/>
                                    </ns6:free_zone_of_manaus_inscptn_id>
                                    <ns6:city_inscription_id>
                                       <xsl:value-of select="codigoIbgeCidade"/>
                                    </ns6:city_inscription_id>
                                    <ns6:state_inscription_id>
                                       <xsl:value-of select="codigoEstadoFederecao"/>
                                    </ns6:state_inscription_id>
                                    <ns6:contributor_type>
                                       <xsl:value-of select="tipoContribuinte"/>
                                    </ns6:contributor_type>
                                    <ns6:tax_exception_type>
                                       <xsl:value-of select="tipoIsencaoTaxa"/>
                                    </ns6:tax_exception_type>
                                    <ns6:iss_contributor>
                                       <xsl:value-of select="contribuidorIss"/>
                                    </ns6:iss_contributor>
                                    <ns6:ipi_contributor>
                                       <xsl:value-of select="contribuidorIpi"/>
                                    </ns6:ipi_contributor>
                                    <ns6:icms_contributor>
                                       <xsl:value-of select="contribuidorIcms"/>
                                    </ns6:icms_contributor>
                                    <ns6:pis_contributor>
                                       <xsl:value-of select="contribuidorPis"/>
                                    </ns6:pis_contributor>
                                    <ns6:cofins_contributor>
                                       <xsl:value-of select="contribuidorCofins"/>
                                    </ns6:cofins_contributor>
                                    <ns6:is_income_range_eligible>
                                       <xsl:value-of select="elegivelReducaoTaxas"/>
                                    </ns6:is_income_range_eligible>
                                    <ns6:is_distributor_manufacturer>
                                       <xsl:value-of select="distribuidorFabricante"/>
                                    </ns6:is_distributor_manufacturer>
                                    <ns6:customers_cnae>
                                       <xsl:value-of select="codigoCnaeCliente"/>
                                    </ns6:customers_cnae>
                                    <xsl:for-each select="PagamentoList">
                                       <ns3:BrFulfilOrdPmtDesc>
                                          <ns3:payment_method>
                                             <xsl:value-of select="metodoPagamento"/>
                                          </ns3:payment_method>
                                          <ns3:payment_amount>
                                             <xsl:value-of select="quantidadePagamento"/>
                                          </ns3:payment_amount>
                                       </ns3:BrFulfilOrdPmtDesc>
                                    </xsl:for-each>
                                    <ns6:transaction_type>
                                       <xsl:value-of select="tipoTransacao"/>
                                    </ns6:transaction_type>
                                 </ns6:BrFulfilOrdCustDesc>
                              </xsl:for-each>
                           </ns2:LocOfFulfilOrdCustDesc>
                        </xsl:for-each>
                     </ns5:FulfilOrdCustDesc>
                  </xsl:for-each>
                  <xsl:for-each select="/ns0:CriarPedidoReservaRequest/OrdemDetalheList">
                     <ns4:FulfilOrdDtl>
                        <ns4:item>
                           <xsl:value-of select="codigoItem"/>
                        </ns4:item>
                        <ns4:order_qty_suom>
                           <xsl:value-of select="quantidadeSolicitadaItem"/>
                        </ns4:order_qty_suom>
                        <ns4:standard_uom>
                           <xsl:value-of select="unidadeMedidaPadrao"/>
                        </ns4:standard_uom>
                        <ns4:transaction_uom>
                           <xsl:value-of select="quantidadeMedidaUtilizada"/>
                        </ns4:transaction_uom>
                        <ns4:substitute_ind>
                           <xsl:value-of select="flagItemPodeSerSubstituido"/>
                        </ns4:substitute_ind>
                        <ns4:unit_retail>
                           <xsl:value-of select="precoVenda"/>
                        </ns4:unit_retail>
                     </ns4:FulfilOrdDtl>
                  </xsl:for-each>
               </ns7:FulfilOrdDesc>
            </tns:messageData>
            <tns:customFlag>
               <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '035', 'customFlag', '')"/>
            </tns:customFlag>
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
