<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://service.ultra.com.br/atacado/PedidoReserva/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDtlRef/v1"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/FulfilOrdRef/v1"
                xmlns:Q4="http://schemas.datacontract.org/2004/07/Wsdl.Integration"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/PedidoReserva/v1/WSDLs/PedidoReservaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CancelarPedidoReservaRequest" namespace="http://service.ultra.com.br/atacado/PedidoReserva/v1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/PedidoReserva/v1/WSDLs/PedidoReservaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 06 15:05:24 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RibMessages>
         <tns:ribMessage>
            <tns:family>
               <xsl:value-of select="'oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '072', 'family', '')"/>
            </tns:family>
            <tns:type>
               <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '072', 'type', '')"/>
            </tns:type>
            <tns:messageData>
               <ns2:FulfilOrdRef>
                  <ns2:customer_order_no>
                     <xsl:value-of select="/ns0:CancelarPedidoReservaRequest/codigoPedidoCliente"/>
                  </ns2:customer_order_no>
                  <ns2:fulfill_order_no>
                     <xsl:value-of select="/ns0:CancelarPedidoReservaRequest/codigoOrdemAtendimentoConfirmado"/>
                  </ns2:fulfill_order_no>
                  <ns2:source_loc_type>
                     <xsl:value-of select="/ns0:CancelarPedidoReservaRequest/localOrigem"/>
                  </ns2:source_loc_type>
                  <ns2:fulfill_loc_type>
                     <xsl:value-of select="/ns0:CancelarPedidoReservaRequest/tipoLocalDestino"/>
                  </ns2:fulfill_loc_type>
                  <ns2:fulfill_loc_id>
                     <xsl:value-of select="/ns0:CancelarPedidoReservaRequest/localDestino"/>
                  </ns2:fulfill_loc_id>
                  <xsl:for-each select="/ns0:CancelarPedidoReservaRequest/CancelaOrdemDetalheList">
                     <ns1:FulfilOrdDtlRef>
                        <ns1:item>
                           <xsl:value-of select="ns0:codigoItem"/>
                        </ns1:item>
                        <ns1:ref_item>
                           <xsl:value-of select="ns0:upcItem"/>
                        </ns1:ref_item>
                        <ns1:cancel_qty_suom>
                           <xsl:value-of select="ns0:quantidadeCanceladaItem"/>
                        </ns1:cancel_qty_suom>
                        <ns1:standard_uom>
                           <xsl:value-of select="ns0:unidadeMedidaPadrao"/>
                        </ns1:standard_uom>
                        <ns1:transaction_uom>
                           <xsl:value-of select="ns0:unidadeMedidaCancelada"/>
                        </ns1:transaction_uom>
                     </ns1:FulfilOrdDtlRef>
                  </xsl:for-each>
               </ns2:FulfilOrdRef>
            </tns:messageData>
            <tns:customFlag>
               <xsl:value-of select="dvm:lookupValue ('oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessage.dvm', 'id', '072', 'customFlag', '')"/>
            </tns:customFlag>
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
