<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/IdentificaServicoRetailIntegracaoBPEL/etStoresFromRMSJMSReference"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://www.oracle.com/retail/integration/base/bo/ItemTcktDesc/v1"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/ItemUDADateDesc/v1"
                xmlns:ns5="http://www.oracle.com/retail/integration/base/bo/ItemUDAFFDesc/v1"
                xmlns:ns8="http://www.oracle.com/retail/integration/base/bo/RelatedItemDesc/v1"
                xmlns:ns11="http://www.oracle.com/retail/integration/base/bo/ItemHdrDesc/v1"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/LocOfItemHdrDesc/v1"
                xmlns:ns4="http://www.oracle.com/retail/integration/localization/bo/BrItemHdrDesc/v1"
                xmlns:ns6="http://www.oracle.com/retail/integration/base/bo/ItemUDALOVDesc/v1"
                xmlns:ns7="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyMfrDesc/v1"
                xmlns:ns9="http://www.oracle.com/retail/integration/base/bo/ItemDesc/v1"
                xmlns:ns10="http://www.oracle.com/retail/integration/base/bo/ISCDimDesc/v1"
                xmlns:ns12="http://www.oracle.com/retail/integration/base/bo/ItemImageDesc/v1"
                xmlns:ns13="http://www.oracle.com/retail/integration/base/bo/ItemSupDesc/v1"
                xmlns:ns14="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1"
                xmlns:ns15="http://www.oracle.com/retail/integration/base/bo/ItemBOMDesc/v1"
                xmlns:ns16="http://www.oracle.com/retail/integration/base/bo/ItemUPCDesc/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/etStoresFromRMSJMSReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/etStoresFromRMSJMSReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JUL 14 18:32:34 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
<ns0:RibMessages>

         <ns0:ribMessage>
            <ns0:family>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:family"/>
            </ns0:family>
            <ns0:type>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:type"/>
            </ns0:type>
            <ns0:id>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:id"/>
            </ns0:id>
            <ns0:ribmessageID>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:ribmessageID"/>
            </ns0:ribmessageID>
            <ns0:routingInfo>
               <ns0:name>
                  <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:routingInfo/ns0:name"/>
               </ns0:name>
               <ns0:value>
                  <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:routingInfo/ns0:value"/>
               </ns0:value>
            </ns0:routingInfo>
            <ns0:publishTime>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:publishTime"/>
            </ns0:publishTime>
            <ns0:messageData>
                  <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:messageData/node()" disable-output-escaping="yes"/>
               </ns0:messageData>
            <ns0:customData>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:customData"/>
            </ns0:customData>
            <ns0:customFlag>
               <xsl:value-of select="/ns0:RibMessages/ns0:ribMessage/ns0:customFlag"/>
            </ns0:customFlag>
         </ns0:ribMessage>
      </ns0:RibMessages>
   </xsl:template>
</xsl:stylesheet>
