<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://service.ultra.com.br/logistica/RecebimentoMercadoria/v1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:Q3="http://canonico.ultra.com.br/infcorp/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:Q2="http://service.ultra.com.br/infcorp/LogIntegration/v1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns3="http://www.oracle.com/retail/integration/base/bo/EXFItemDesc/v1"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns4="http://www.oracle.com/retail/integration/custom/bo/ExtOfReceiptDesc/v1"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/RecebimentoMercadoriaIntegracaoBPEL/etReceivingJMSReference"
                xmlns:ns2="http://www.oracle.com/retail/integration/base/bo/ReceiptDesc/v1"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns5="http://www.oracle.com/retail/integration/base/bo/ItemTcktDesc/v1"
                xmlns:ns6="http://www.oracle.com/retail/integration/base/bo/ItemUDADateDesc/v1"
                xmlns:ns9="http://www.oracle.com/retail/integration/base/bo/ItemUDAFFDesc/v1"
                xmlns:ns12="http://www.oracle.com/retail/integration/base/bo/RelatedItemDesc/v1"
                xmlns:ns15="http://www.oracle.com/retail/integration/base/bo/ItemHdrDesc/v1"
                xmlns:ns7="http://www.oracle.com/retail/integration/base/bo/LocOfItemHdrDesc/v1"
                xmlns:ns8="http://www.oracle.com/retail/integration/localization/bo/BrItemHdrDesc/v1"
                xmlns:ns10="http://www.oracle.com/retail/integration/base/bo/ItemUDALOVDesc/v1"
                xmlns:ns11="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyMfrDesc/v1"
                xmlns:ns13="http://www.oracle.com/retail/integration/base/bo/ItemDesc/v1"
                xmlns:ns14="http://www.oracle.com/retail/integration/base/bo/ISCDimDesc/v1"
                xmlns:ns16="http://www.oracle.com/retail/integration/base/bo/ItemImageDesc/v1"
                xmlns:ns17="http://www.oracle.com/retail/integration/base/bo/ItemSupDesc/v1"
                xmlns:ns18="http://www.oracle.com/retail/integration/base/bo/ItemSupCtyDesc/v1"
                xmlns:ns19="http://www.oracle.com/retail/integration/base/bo/ItemBOMDesc/v1"
                xmlns:ns20="http://www.oracle.com/retail/integration/base/bo/ItemUPCDesc/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RecebimentoMercadoriaV1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="NotificarRecebimentoMercadoriaRequest" namespace="http://service.ultra.com.br/logistica/RecebimentoMercadoria/v1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/Extrafarma/Retail/Comum/v1/Schemas/MetaInformacao.xsd"/>
            <oracle-xsl-mapper:rootElement name="MetaInformacao"
                                           namespace="http://service.ultra.com.br/infcorp/LogIntegration/v1"/>
            <oracle-xsl-mapper:param name="MetaInformacaoVariable.parameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/etReceivingJMSReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RibMessages" namespace="http://www.oracle.com/retail/integration/rib/RibMessages"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUN 22 15:26:35 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="MetaInformacaoVariable.parameters"/>
   <xsl:template match="/">
      <tns:RibMessages>
         <tns:ribMessage>
            <tns:family>
              <xsl:value-of select='dvm:lookupValue ("oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessageDVM.dvm", "id", "061076100", "family", "receiving" )'/>
            </tns:family>
            <tns:type>
              <xsl:value-of select='dvm:lookupValue ("oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessageDVM.dvm", "id", "061076100", "type", "receiptcre" )'/>
            </tns:type>
            <tns:id>
               <xsl:value-of select="/ns0:NotificarRecebimentoMercadoriaRequest/codigoAgendamento"/>
            </tns:id>
            <tns:ribmessageID>
               <xsl:value-of select="concat('ERPImifarma_receiving_sub_1|', xp20:current-dateTime(),'|' ,$MetaInformacaoVariable.parameters/Q2:MetaInformacao/Q2:idControle)"/>
            </tns:ribmessageID>
            <tns:publishTime>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:publishTime>
            <tns:messageData>
               <ns2:ReceiptDesc>
                  <ns2:schedule_nbr>
                     <xsl:value-of select="string(/ns0:NotificarRecebimentoMercadoriaRequest/codigoAgendamento)"/>
                  </ns2:schedule_nbr>
                  <xsl:for-each select="/ns0:NotificarRecebimentoMercadoriaRequest/RecebimentoList">
                     <ns2:Receipt>
                        <ns2:dc_dest_id>
                           <xsl:value-of select="string(codigoFilial)"/>
                        </ns2:dc_dest_id>
                        <ns2:po_nbr>
                           <xsl:value-of select="string(codigoPedidoTransferencia)"/>
                        </ns2:po_nbr>
                        <ns2:document_type>
                           <xsl:value-of select="tipoRecebimento"/>
                        </ns2:document_type>
                        <ns2:ref_doc_no>
                           <xsl:value-of select="string(numeroNota)"/>
                        </ns2:ref_doc_no>
                        <xsl:for-each select="RecebimentoDetalheList">
                           <ns2:ReceiptDtl>
                              <ns2:item_id>
                                 <xsl:value-of select="string(codigoProduto)"/>
                              </ns2:item_id>
                              <ns2:unit_qty>
                                 <xsl:value-of select="format-number(quantidadeProduto,'############.0000')"/>
                              </ns2:unit_qty>
                              <ns2:receipt_xactn_type>
                                 <xsl:value-of select="tipoRecebimentoProduto"/>
                              </ns2:receipt_xactn_type>
                              <ns2:receipt_date>
                                 <xsl:value-of select="dataRecebimento"/>
                              </ns2:receipt_date>
                              <ns2:receipt_nbr>
                                 <xsl:value-of select="string(codigoLote)"/>
                              </ns2:receipt_nbr>
                              <ns2:distro_nbr>
                                 <xsl:value-of select="string(codigoPedidoTransferencia)"/>
                              </ns2:distro_nbr>
                              <xsl:for-each select="ItemList">
                                 <ns4:ExtOfReceiptDtl>
                                    <xsl:for-each select="LoteItemList">
                                       <ns3:EXFItemDtl>
                                          <ns3:volume>
                                             <xsl:value-of select="string(codigoVolumeProduto)"/>
                                          </ns3:volume>
                                          <xsl:for-each select="LoteItemDetalheList">
                                             <ns3:EXFLotInfoDesc>
                                                <ns3:lot_id>
                                                   <xsl:value-of select="codigoLote"/>
                                                </ns3:lot_id>
                                                <ns3:manufacture_date>
                                                   <xsl:value-of select="dataFabricacaoLote"/>
                                                </ns3:manufacture_date>
                                                <ns3:expiration_date>
                                                   <xsl:value-of select="dataValidade"/>
                                                </ns3:expiration_date>
                                                <ns3:lot_qty>
                                                   <xsl:value-of select="format-number(quantidadeLote,'############.0000')"/>
                                                </ns3:lot_qty>
                                             </ns3:EXFLotInfoDesc>
                                          </xsl:for-each>
                                          <xsl:for-each select="ImeiList">
                                             <ns3:EXFImei>
                                                <ns3:imei>
                                                   <xsl:value-of select="imeiProduto"/>
                                                </ns3:imei>
                                             </ns3:EXFImei>
                                          </xsl:for-each>
                                       </ns3:EXFItemDtl>
                                    </xsl:for-each>
                                 </ns4:ExtOfReceiptDtl>
                              </xsl:for-each>
                           </ns2:ReceiptDtl>
                        </xsl:for-each>
                        <ns2:receipt_type>
                           <xsl:value-of select="nivelRecebimento"/>
                        </ns2:receipt_type>
                        <ns2:from_loc>
                           <xsl:value-of select="number(substring(localOrigemRemessa ,1,10))"/>
                        </ns2:from_loc>
                        <ns2:from_loc_type>
                           <xsl:value-of select="tipoLocalOrigem"/>
                        </ns2:from_loc_type>
                     </ns2:Receipt>
                  </xsl:for-each>
               </ns2:ReceiptDesc>
            </tns:messageData>
            <tns:customFlag>
               <xsl:value-of select='dvm:lookupValue ("oramds:/apps/Extrafarma/Retail/Comum/v1/Resource/ValoresRibMessageDVM.dvm", "id", "061076100", "customFlag", "F" )'/>
            </tns:customFlag>
         </tns:ribMessage>
      </tns:RibMessages>
   </xsl:template>
</xsl:stylesheet>
