<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CriarTransferenciaMercadoriaCD"
     targetNamespace="http://service.ultra.com.br/logistica/CriarTransferenciaMercadoriaCD/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://service.ultra.com.br/logistica/CriarTransferenciaMercadoriaCD/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="TransferenciaMercadoriaCDDBBPEL">
        <plnk:role name="CriarTransferenciaMercadoriaCDPortType" portType="tns:CriarTransferenciaMercadoriaCDPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://service.ultra.com.br/logistica/CriarTransferenciaMercadoriaCD/v1"
         location="CriarTransferenciaMercadoriaCDV1.wsdl"/>
</wsdl:definitions>
