<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MercadoriaAtacado"
     targetNamespace="http://service.ultra.com.br/atacado/MercadoriaAtacado/v1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://service.ultra.com.br/atacado/MercadoriaAtacado/v1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://service.ultra.com.br/infcorp/LogIntegration/v1"
    >
    <plnk:partnerLinkType name="MercadoriaAtacadoDBBPEL">
        <plnk:role name="MercadoriaAtacadoPortType" portType="tns:MercadoriaAtacadoPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://service.ultra.com.br/atacado/MercadoriaAtacado/v1" location="MercadoriaAtacadoV1.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://service.ultra.com.br/infcorp/LogIntegration/v1" schemaLocation="oramds:/apps/Extrafarma/Retail/Comum/v1/Schemas/MetaInformacao.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
