<wsdl:definitions
     name="etASNOutJMSReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/ExpedicaoMercadoriaIntegracaoBPEL/etASNOutJMSReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/AppExtrafarmaSOA/ExpedicaoMercadoriaIntegracaoBPEL/etASNOutJMSReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://service.ultra.com.br/logistica/ExpedicaoMercadoria/v1"
    >
  <plt:partnerLinkType name="Posta_Mensagem_plt" >
    <plt:role name="Posta_Mensagem_role" >
      <plt:portType name="tns:Posta_Mensagem_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://service.ultra.com.br/logistica/ExpedicaoMercadoria/v1"
                schemaLocation="../../../MDS/SOA/apps/Extrafarma/Retail/ExpedicaoMercadoria/v1/Schemas/ExpedicaoMercadoriaEBMV1.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Posta_Mensagem_msg">
        <wsdl:part name="body" element="imp1:NotificarExpedicaoMercadoriaRequest"/>
    </wsdl:message>
    <wsdl:portType name="Posta_Mensagem_ptt">
        <wsdl:operation name="Posta_Mensagem">
            <wsdl:input message="tns:Posta_Mensagem_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
